---
title: "REDUCED-RANK REGRESSION IN HMSC: Pollination Traits and Mean Number of Flower Visits at the Population Level"
---

```{r include=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(tidyr)
library(Hmsc)
library(stringr)
```

# Load Data for Reduced-Rank Regression

```{r}
data_flower_traits <- readRDS(paste0(here::here("Data/Data_Pollination_Traits_Master.rds")))
```

```{r}
data_pollinators <- readRDS(paste0(here::here("Data/Data_Pollinators_Master.rds")))
```

```{r}
data_reduced_rank_regression <- list(Flower_Traits = data_flower_traits, Pollinators = data_pollinators)
```

# Prepare Data for Reduced-Rank Regression

## Mean Number of Flower Visits per Population

```{r}
data_flower_visits_mean <- data_reduced_rank_regression$Pollinators %>% 
  group_by(Population) %>% 
  summarise(across(Bombus_Queen:Syrphidae, mean), .groups = "drop")
```

## Mean Pollination Traits per Population

```{r}
data_flower_traits_mean <- data_reduced_rank_regression$Flower_Traits %>% 
  group_by(Population) %>% 
  summarise(across(Stem_Height:NSD, ~ mean(.x, na.rm = TRUE)), .groups = "drop")
```

```{r}
data_flower_traits_mean <- data_flower_traits_mean %>% 
  mutate(log_Stem_Height = log(Stem_Height),
         log_Total_Flowers = log(Total_Flowers),
         log_Corolla_Diameter = log(Corolla_Diameter),
         log_Tube_Width = log(Tube_Width),
         log_Tube_Length = log(Tube_Length),
         log_NSD = log(NSD)) %>% 
  select(Population, log_Stem_Height, log_Total_Flowers, log_Corolla_Diameter, log_Tube_Width, log_Tube_Length, log_NSD)
```

# Assemble Data for Reduced-Rank Regression

```{r}
data_flower_traits_flower_visits_population <- merge(data_flower_traits_mean,
                                                     data_flower_visits_mean,
                                                     by = "Population",
                                                     all = TRUE)
```

```{r}
data_pollinator_population_mean <- data_flower_traits_flower_visits_population %>% 
  select(Population, Bombus_Queen:Syrphidae)
```

```{r}
data_pollinator_population_variance_scaled <- data_pollinator_population_mean %>% 
  mutate(across(Bombus_Queen:Syrphidae, ~ (. - mean(.)) / sd(.)))
# each value in the column (.) has the column mean subtracted (mean(.)) and then divided by the column standard deviation (sd(.))
# mean of zero and standard deviation of one
```

# Basic Data Information for Reduced-Rank Regression

```{r}
RRR_info_intercept <- data.frame(Intercept = rep(1, nrow(data_flower_traits_flower_visits_population)))
```

```{r}
RRR_info_study_design <- data_flower_traits_flower_visits_population %>% 
  select(Population) %>% 
  mutate_at(vars(Population),
            as.factor)
```

## Define Random Levels

```{r}
RRR_info_random_level_population <- HmscRandomLevel(units = unique(RRR_info_study_design$Population))
```

## Define Model Formula

```{r}
RRR_info_model_formula = ~ 1
```

```{r}
RRR_info_model_formula_pollinator_groups <- as.formula(paste("~", "- 1 +", paste0(colnames(data_pollinator_population_mean %>% 
                                                                                             select(Bombus_Queen:Syrphidae)),
                                                                                  collapse = "+")))
```

# Define HMSC Model

```{r}
identical(data_flower_traits_mean$Population,
          data_flower_visits_mean$Population,
          RRR_info_study_design$Population)
```

```{r}
RRR_model_abundance <- Hmsc(Y = data_flower_traits_mean %>%
                              select(log_Stem_Height:log_NSD),
                            XData = RRR_info_intercept,
                            XFormula = RRR_info_model_formula,
                            XRRRData = data_pollinator_population_variance_scaled %>% 
                              select(Bombus_Queen:Syrphidae),
                            XRRRFormula = RRR_info_model_formula_pollinator_groups,
                            ncRRR = 2,
                            distr = "normal",
                            studyDesign = RRR_info_study_design,
                            ranLevels = list(Population = RRR_info_random_level_population))
```

# Sample MCMC

```{r}
model_HMSC_samples <- 1000
model_HMSC_thin <- 100
model_HMSC_adaptNf <- ceiling(0.4 * model_HMSC_samples  * model_HMSC_thin)
model_HMSC_transient <- ceiling(0.5 * model_HMSC_samples * model_HMSC_thin)
```

```{r}
RRR_model_abundance <- sampleMcmc(RRR_model_abundance,
                                  samples = model_HMSC_samples,
                                  thin = model_HMSC_thin,
                                  adaptNf = rep(model_HMSC_adaptNf, 1),
                                  transient = model_HMSC_transient,
                                  nChains = 2,
                                  nParallel = 2)
```